image: eclipse-temurin:21-jdk

stages:
  - build
  - test
  - package
  - deploy

build_job:
  stage: build
  script:
    - echo "Compiling the code..."
    - ./mvnw -f java_training/pom.xml compile
  artifacts:
    paths:
      - java_training/target/

test_job:
  stage: test
  script:
    - echo "Running Maven tests..."
    - ./mvnw -f java_training/pom.xml test
  artifacts:
    when: always
    reports:
      junit: java_training/target/surefire-reports/TEST-*.xml

package_job:
  stage: package
  script:
    - echo "Packaging the application..."
    - ./mvnw -f java_training/pom.xml package -DskipTests
  artifacts:
    paths:
      - java_training/target/*.jar
    expire_in: 1 week

deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache ansible
    - ansible-playbook -i hosts playbook.yml